### PR TITLE
Join stable improvements to functionality to master branch

### PR DESCRIPTION
**Pull request by BrydenFrancesca**
Incorporating @sarahmoody1's suggestions of new features, and a fix to allow conversion of documents with no images.

### CODE REVIEW

**Review by aidanmews — COMMENTED** [review]
Presumably pre-release is now supposed to be in bold?

**Comment by ms130** [comment]
Hi @BrydenFrancesca, I'm not able to add any commits here (correct me if I'm wrong) or create a new branch from the dev one, however I've tried `convert_rmd()` without an images file specified, and that works. (If I were being super pedantic, should the function be called `convert_md()` instead since it works on md files, but feel free to ignore this?).

One suggestion: your Travis tests are failing since R CMD is throwing up a warning due to documentation issues with `add_summary_table` and the internal function `bold_key_words`. I changed `key_words` to `key_words_remove` on line 4 of `internal_functions.R` (the `bold_key_words` function), and then ran a `devtools::document()` which updated the docs for `add_summary_table.Rd` and `bold_key_words.Rd`. That removed any R CMD warnings, and should mean your Travis tests pass (since you've got it configured that warnings are flagged as errors). Hope that helps.

**Comment by BrydenFrancesca** [comment]
@ms130 Hi Marco, thanks for this; have added you as an admin to the repo and would really appreciate it if you could push the changes you mentioned. Agree about the naming of the convert_rmd function, naming was set when it was just code I was using myself, and to distinguish from the convert_md function of the govspeakr package. I think it could be changed, but the convert_rmd function would have to be retained for a couple of versions with a warning that it was becoming obsolete?

**Comment by ms130** [comment]
Will leave the retiring of `convert_rmd` in favour of `convert_md` for a later date

**Pull request merged**
