### PR TITLE
Feature/refactoring

### LINKED ISSUE #25: Could add a code linter
If that's desired could be run either locally, or automatically upon pull request with GH Actions.

### PR DESCRIPTION
**Pull request by BrydenFrancesca**
So, I've finally bitten the bullet and done a serious upgrade to the features in this! New stuff includes:

- [ ] Dropping the endless dependencies on "asis" settings, funky native md content now works right out of the box
- [ ] Removing the need to specify where you're keeping your images. This means it no longer requires numbering of code chunks, fixes issues we've been having recently if your rmarkdown isn't stored in the root of a project, and fixes issues of conversion when bulletins don't include images
- [ ] Unit tests! Don't get too excited, I did as many as I was mentally prepared to, which is not enough.
- [ ] Builds in a linter

### CODE REVIEW

**Comment by BrydenFrancesca** [comment]
@ms130 would appreciate a review on this one as it's a bit of an upgrade! Will do some testing early next week and then a merge, so can tag you into the dev -> master if you'd prefer.

Also, a thought; not sure if this gets much use in MoJ any more? If it's largely obsolete we can look to shift it over to DfT ownership (where it still gets a lot of love), and I can stop nagging you for peer review?

**Comment by ms130** [comment]
> @ms130 would appreciate a review on this one as it's a bit of an upgrade! Will do some testing early next week and then a merge, so can tag you into the dev -> master if you'd prefer.
> 
> Also, a thought; not sure if this gets much use in MoJ any more? If it's largely obsolete we can look to shift it over to DfT ownership (where it still gets a lot of love), and I can stop nagging you for peer review?

I think it is still used in MoJ, although I don't have any figures. But since you've moved to DfT, maybe it does make sense for the ownership to follow you there, as long as it's still accessible to MoJ users!

**Comment by ms130** [comment]
Some thoughts @BrydenFrancesca:

- [x]  Does the Readme or any function documentation need updating, after these changes?
- [x]  Running convert_rmd() with `Figure 1
!`
I get an extra `!` on it's own on another line. Is that an issue?
- [x]  There's a merge conflict to fix, not sure if that happened because I merged the linter branch into dev first
- [ ]  Could help to add a "Returns" section in the function roxygen docs (and examples where sensible) with a brief description of what the function returns.
- [x]  Could put the 'installation' section in the readme, before the 'Usage' one
- [x]  Could add a few comments to the Usage section, with an example of calling the convert function, and saying a '_converted.md' will be written
- [x]  Maybe I'm a bit thick, but it wasn't immediately obvious which functions I should use in a .Rmd file, and which not. If I understand, the convert is run on the command line, and the rest in a Rmd file? Might help to make this obvious in the Readme
- [x]  Small R CMD issue, but I'm getting the undefined global variable Note for 'data' and 'write.csv'. It suggests adding `importFrom("utils", "data", "write.csv")` though not sure if they're from the utils package. Up to you whether you can bothered to fix this note

Otherwise, looks good to me!

**Comment by BrydenFrancesca** [comment]
Cheers @ms130, some great comments here! I'm going to split the returns/examples point off into a new issue as I think it's more than a quick fix, but v important.

Will give some thought to moving ownership, at the minute it'd be a right pain as I've got two different github accounts; you'd need to get a tame AP engineer to add my dft one to the repo! Also issues with people needing to update their paths to it, plus a potential name change?

**Comment by ms130** [comment]
The readme is looking great now @BrydenFrancesca!

**Pull request merged**
